### ISSUE TITLE
SNAP HLS Support: How to deal with interrupts, ContextID, AXI-User-bits and HLS to SNAP interfaces

### ISSUE THREAD

**Issue by fhaverkamp** [open-power/snap#179]
I think we urgently need a discussion how we need to adopt the SNAP to HLS interface regarding:
* Interrupts
* Dealing with AFU-conextids
* Offering SNAP functions in HLS context, e.g. sending an interrupt to the host or how to access NVMe storage, and maybe accessing a timer register

We see now those mechanisms going into the master git branch and Sven adding backward compatibility workarounds,  which would not be needed if the direction on how to change our way to deal with HLS actions would be clarified and adjusted when the other changes happen.

**Comment by bmesnet** [comment]
Is there still a need to keep this issue opened ?

**Comment by jsvogt** [comment]
Solved with HLS wrapper long time ago.
AXI user bits are not supported on HLS by Xilinx, we have a circumvention for context ID.
Also byte-enables on AXI not supported.
