### ISSUE TITLE
Memory Free Fails after capi-flash-script

### ISSUE THREAD

**Issue by ibm-genwqe** [open-power/snap#185]
Scenario to reproduce:
1.) update KU3 with new bitstream using "capi-flash-script xxx.bin"
      - capi-flash-script reset's card after flashing e.g. (echo 1 > /sys/class/cxl/card0/reset)
      - Wait some sec 
2.) run snap_maint to config Card
3.) run "./tools /stage2 -a2 -A64 -S8 -v"
     - Ends with "*** Error in `./tools/stage2': free(): invalid pointer: 0x00000100389301c0 ***"
3.) try same command as in (3) but use -A 128
    - No error
4.) Reset Card again (echo 1 > /sys/class/cxl/card0/reset)
5.) run same command (3)
     Memory free problem is gone.

The card seems to get into some bad state where Memory is overwritten in some rare cases after 
Card Flash.

**Comment by jsvogt** [comment]
Does this still exist? Please re-test with the current PSL versions.
I assume this problem isn't related to the CAPI/PSL Memory alloc/dealloc issue (issue with TLBI, requiring Linux cxl kernel extension fix).

**Comment by ibm-genwqe** [comment]
Duplicate:
https://github.com/open-power/snap/issues/387

**Comment by ibm-genwqe** [comment]
Closing this issue, we still beed a circumvention for FGT Code
