### ISSUE TITLE
HLS memcopy : reading XXX from DDR when not aligned size (different than 64B, 64kB,...)

### ISSUE THREAD

**Issue by bmesnet** [open-power/snap#240]
Test done on master branch. 
Test is to move X bytes from Host to DDR and back from DDR to Host
test failure with X = 2,3,8,32,99
test success with X = 64, 64K
#!/bin/bash
      export DNUT_TRACE=0xff
      dd if=/dev/urandom of=t1 bs=1 count=8

      $DONUT_ROOT/software/tools/snap_maint -v
      $DONUT_ROOT/software/examples/demo_memcopy -vv -t2500 -I -i t1 -D CARD_DRAM -d 0x0
      $DONUT_ROOT/software/examples/demo_memcopy -vv -t2500 -I -s 8 -A CARD_DRAM -a 0x0 -o t2
      diff t1 t2

      if diff t1 t2 >/dev/null;then echo "RC=$rc file_diff ok";else
        echo -e "$t RC=$rc file_diff is wrong\n$del";exit 1;
      fi
=> Read from Host is always ok
=> write to DDR is always ok
=> read from DDR shows XXX if size is not aligned
=> write to Host is ok
AET is in : /afs/vlsilab.boeblingen.ibm.com/projects/fpga/framework/mesnet/donut/hardware/sim/save_waves/20170510_155026

**Comment by joergkayser** [comment]
@bmesnet, with branch=master hash=beadb7e 2017-05-30 I can confirm, that this error is gone. Do you want me to close the ticket ?

**Comment by bmesnet** [comment]
In hls_search.cpp, write to DDR is done with 64Bytes aligned words to solve the issue
