### ISSUE TITLE
Build : display/set the HLS release used

### ISSUE THREAD

**Issue by bmesnet** [open-power/snap#273]
When doing a build (simulation or image), the compilation of the HLS can use a different release level than the Vivado release used for chip. The Vivado HLS release will grow much more quicker than the Vivado tool to take advantage of the bug corrections, and has no incidence on the build of the chip.
As this time the only way to do it is to pre-compile separately the HLS files before the build with the appropriate release, or by default they will take the Vivado release
- Can we use a different variable to separate these ? (actually in ibm_settings_for_snap file)
- Can we display the HLS release used during the build ?
Thx

**Comment by ThomasFuchs** [comment]
@bmesnet 
The current flow prints out the following message during the SNAP configuration phase:
[CREATE_ENVIRONMENT..] start Thu Sep  7 10:53:29 CEST 2017
	                                     using Vivado v2016.4 (64-bit)

Is this sufficient?

**Comment by bmesnet** [comment]
@ThomasFuchs 
No the Vivado release level needs to be independent from the Vivado HLS release level since HLS release needs to be at the latest to get all bugs solved. Changing HLS release is immediate while changing Vivado release has a lot of dependencies and must be tested deeply

**Comment by jsvogt** [comment]
By default the latest Vivado should be ok for HLS as well. For the short times when a newer HLS is required, there is a workaround to compile the HLS files manually before starting the snap framework build process.
=> rejecting this change request
