### ISSUE TITLE
Building the image with NVMe doesn't work without DENALI set

### ISSUE THREAD

**Issue by jsvogt** [open-power/snap#287]
When building with NVME_USED=TRUE, snap_settings complains about missing DENALI environment variable for the Denali include directory
`### WARNING ### Setting of NVME_USED=TRUE but DENALI not set!`

It must be possible to build FPGA images with the NVMe host controller, even without a Denali environment.

**Comment by ThomasFuchs** [comment]
it is part of the master branch

**Comment by joergkayser** [comment]
As Simulation always needs DENALI set, I cannot really help with the validation of this issue. Let us do this in image build. Putting me off the assignee list

**Comment by boekholt** [comment]
I can confirm that image build with NVMe works now also in case `$DENALI` or other Denali related environment variables are not set.
@jsvogt please close this issue.

**Comment by jsvogt** [comment]
Thanks, closing this issue.
