### ISSUE TITLE
snap_maint : display action release level

### ISSUE THREAD

**Issue by bmesnet** [open-power/snap#313]
when running command ./software/tools/snap_maint -C1 -v
Information on Action is the following : 
   Short      Action Type
   0          0x10141000   HLS Memcopy
Could it be possible to display the **Release level** of the action which is read by snap_maint at the same time?
Thx

**Comment by ibm-genwqe** [comment]
I can add this, NP

**Comment by ibm-genwqe** [comment]
i pushed some code to debug.

**Comment by bmesnet** [comment]
code cehcked ok. No need to keep this issue opened. thanks
