### ISSUE TITLE
HLS_search: wrong results with snap_search

### ISSUE THREAD

**Issue by joergkayser** [open-power/snap#315]
working with branch=master and action=hls_search. I am creating a small file (random or uniform data)  of n bytes and search one char. Expect n hits on uniform data and 0..n hits on random data

for size in 1 2; do 
  char=$(cat /dev/urandom|tr -dc 'a-zA-Z0-9'|fold -w 1|head -n 1)     # random char to search for
  cat /dev/urandom|tr -dc 'a-zA-Z0-9'|fold -w ${size}|head -n 1 >${size}.rnd   # random ASCII data 
  cmd='print("A" * '${size}', end="")'; python3 -c "$cmd" >${size}.uni              # uniform data 
  count=$(fgrep -o $char ${size}.rnd|wc -l);                                                      # expected chars in file
  snap_search -m2 -p${char} -i${size}.rnd -E${count} -t500 -v                          # random search
  snap_search -m2 -pA -i${size}.uni -E${size} -t500 -v                                      # uniform search
done

The test fails, as soon as it expects >0 hits:
snap_search -pA -i1.uni -E1
INFO:Connecting to host 'hdcl070.boeblingen.de.ibm.com' port 16384
Start Step1 (Copy source data from Host to DDR) ..............
INITIALIZATION : move 1 bytes from Host mem to DDR
Step 1 took 9466297 usec
Searching : iteration number 0 1
Start Step3 (Do Search by hardware, in DDR) .......
Naive method (1) 
dsize = 1 - psize = 1 
warn: Verification failed expected 1 but found 0 patterns

**Comment by bmesnet** [comment]
Good corner case! I'll have a look to that

**Comment by bmesnet** [comment]
ok this is corrected and Jörg tested it ok
