### ISSUE TITLE
Hardware/README.md : correct reference to action_examples/memcopy

### ISSUE THREAD

**Issue by bmesnet** [open-power/snap#323]
Several times appears reference to ACTION_ROOT=$SNAP_ROOT/hardware/action_examples/memcopy
which doesn't exist anymore. Can you please correct it?
I guess it should be $SNAP_ROOT/hardware/action_examples/hdl_example
thx

**Comment by jsvogt** [comment]
The fixes are in branch jsv_README

**Comment by bmesnet** [comment]
Sounds ok. Thx
