### ISSUE TITLE
Setup: simulation fails if gcc and xterm are not available

### ISSUE THREAD

**Issue by ThomasFuchs** [open-power/snap#341]
To run SNAP gcc and xterm is  required, but the availability  will not checked.

**Comment by fhaverkamp** [comment]
Can you make the title of this bug more descriptive, please?
Do you expect some dependency checking to be done? I mean libc, grep, perl, sed, ... maybe more. Do you really expect us to maintain such a list of dependencies some place? If this would be a distro package we could use the dependency checking for software some folks use autoconfigs "./configure" or alike. I could imagine that those tools/libs are located at different places for different distros making the checking complicated especially for libs.

**Comment by fhaverkamp** [comment]
I do not see for which purpose we need xterm?

**Comment by ThomasFuchs** [comment]
simulation requires a xterm

**Comment by jsvogt** [comment]
Xterm is listed in the readme now. Is this good enough, so we can close this?
