### ISSUE TITLE
HW: Remove inactive logic for "64byte swap" problem circumvention

### ISSUE THREAD

**Issue by boekholt** [open-power/snap#362]
With change #360 the circumvention for the 64byte swap problem got disabled.
When we know that we have a stable PSL fix for this, the signals flip_bit_q and flip_bit_valid_q together with the related logic should be removed.

**Comment by ibm-genwqe** [comment]
Branch https://github.com/open-power/snap/tree/RC_flip_bit_4_fgt did fix this problem on FGT Card.
See also https://github.com/open-power/snap/issues/387

**Comment by boekholt** [comment]
FGT still requires the "flip bit circumvention". Therefore, the corresponding logic can't be removed, yet.
We can reopen this issue as soon as the FGT PSL logic is fixed.
