### ISSUE TITLE
HW snap_build.tcl: Problems with extracting timing information

### ISSUE THREAD

**Issue by boekholt** [open-power/snap#375]
In snap_build.tcl timing information gets extracted in order to decide if the image build was successful.
Here we are interested in the WNS (Worst Negative Slack). The variable name and the messages indicate that we are looking at the TNS (Total Negative Slack).

The extraction leads to errors for 0.000 ns WNS. In this case an empty result gets produced which then leads to a tcl interpeter error for the following conditional expression: `[expr $TIMING_TNS >= 0 ]` .

**Comment by jsvogt** [comment]
Naming: Changing TIMING_TNS to TIMING_WNS. 
The WNS was always used for comparison, not the TNS (as originally planned).
Suppression of leading zeroes in the sed expression led to this bug.
