### ISSUE TITLE
SNAP Action: Move each action type hard- and software part into one subdirectory

### ISSUE THREAD

**Issue by fhaverkamp** [open-power/snap#379]
E.g.

````
actions/hls_memcopy/hardware
                 `- software
                 `- shared
````

Feel free to add more ideas here.

The scattering of the action code was rated not optimal by our HPI and AlphaData partners.

**Comment by luyong6** [comment]
I like this idea very much. Shall we move?

**Comment by fhaverkamp** [comment]
Bruno just told me to proceed with a proposal. The HPI folks wanted it too but I have not seen their proposal yet. Let use try to put something together and discuss it during tryout.

**Comment by fhaverkamp** [comment]
Thanks to all those contributing to this larger effort. I think we did well including this so quickly.
