### ISSUE TITLE
snap_example returns RC=0 despite of errors

### ISSUE THREAD

**Issue by joergkayser** [open-power/snap#391]
When I run snap_example -a2 -A <non64b number>, I get RC=0 and the msg
     align: 1924 must be a multible of 64
In this case the RC must be non_zero

If I run snap_example_ddr -s0x1000 -e4324 -b228 -i1, I get RC=0 and the msgs
     Error@: 0x00000000000010c0 Expect: 0x08edbdab79838cb2 Read: 0x0000000000000000
In this case the RC must be non_zero. If the -b needs to be a multiple of 64B, this has to be explained in the help screen.

**Comment by ibm-genwqe** [comment]
I will fix this in "SW_rc_fix" branch

**Comment by ibm-genwqe** [comment]
Fixed, merged into master

**Comment by ibm-genwqe** [comment]
sorry, Jörg, please close this

**Comment by joergkayser** [comment]
working fine. Thx
