### ISSUE TITLE
HLS code times out during allocation of action

### ISSUE THREAD

**Issue by joergkayser** [open-power/snap#397]
snap_intersect, snap_search and probably other apps fail to attach the action and report a timeout. Please check the attach process and also display the source of the "Timer expired!" message (attach timeout or execution timeout)
Thanks

**Comment by ibm-genwqe** [comment]
Fix will go into branch "SW_attach_timeout"

**Comment by fhaverkamp** [comment]
Thanks Eberhard.

**Comment by joergkayser** [comment]
tested or, please merge

**Comment by ibm-genwqe** [comment]
fixed, code in Master

**Comment by joergkayser** [comment]
works fine now. Thx
