### ISSUE TITLE
demo_memcopy: AERROR leads to hang

### ISSUE THREAD

**Issue by joergkayser** [open-power/snap#41]
demo_memcopy is using addresses outside of the allocated memory range.
If this happens during a partial cachline write request, then the donut code receives AERROR and tries in an endless loop to recover from this scenario with ST_RESTART. This leads to a software timeout
see /afs/bb/proj/fpga/framework/jkayser/donut_opencl/hardware/sim/ies/20161116_143618/

**Comment by jsvogt** [comment]
Will be fixed with the CAPI 2.0 / Performance DMA redesign

**Comment by bmesnet** [comment]
Hi @jsvogt . Do you confirm that this issue is fixed ?

**Comment by bmesnet** [comment]
For me this is an old issue already fixed => closing this issue
