### ISSUE TITLE
Config: remove Kconfig dependencies 

### ISSUE THREAD

**Issue by ThomasFuchs** [open-power/snap#438]
The SNAP configuration (make snap_env) only works if the following Linux packages are installed:

yum groupinstall "Development Tools"
yum install ncurses-devel

Is it possible to use Kconfig without this?

**Comment by boekholt** [comment]
Please have a look at pull request #443 which is addressing this issue.

**Comment by boekholt** [comment]
We did decide to live with the dependency to the Linux kernel sources and to the ncurses library.
