### ISSUE TITLE
PR flow: Support for Nallatech FGT

### ISSUE THREAD

**Issue by kenhill** [open-power/snap#440]
This branch has initial PRFLOW support for FlashGT board:

 `prflow_fgt_update` 

It was tested building `hls_nvme_memcopy` with `cloud_base`. 

Should this be pulled into branch `RC_fix_config`?

**Comment by boekholt** [comment]
Hi Ken,
sure - please go ahead and create a pull request into RC_fix_config.

**Comment by kenhill** [comment]
Included in #433
