### ISSUE TITLE
Configuration menu : save/load with non default name "config" doesn't work

### ISSUE THREAD

**Issue by acastellane** [open-power/snap#501]
Hello,
When user saves its configuration with a different name than default "config", like "config01", it seems properly saved, since you can recall it (if no clean_config was performed?) , but the configuration you obtain when you exit is not a valid one, as it seems default "config" files are not written.
Proposal1 : Either inform user (not the best but the least we can do), or update also the default "config" after a "save" into a different names with a note to user (prefered).
Note : Do we want to keep or suppress the configurations files when doiing a clean config ?
Best regards
SNAP IS COOL !!

**Comment by boekholt** [comment]
kconfig is a standalone tool that the SNAP config make process and scripts are using as is. The SNAP scripts have no means to detect that the user did save a configuration into an alternate file. I also do not see a way to prevent the kconfig tool from allowing that w/o changing the kconfig sources (which we do not have in our hands).
In other words: I do not see a solution for your issue.
