### ISSUE TITLE
add the $SNAP_ROOT/software/tools to PATH variable

### ISSUE THREAD

**Issue by bmesnet** [open-power/snap#502]
To ease customer's experience, would it be possible to add the $SNAP_ROOT/software/tools to PATH ?
This would help using the **snap_maint** and the **snap_find_card** from anywhere in simulation but also while executing the action program on Power8 server
Thanks

**Comment by boekholt** [comment]
What do you think would be the appropriate place to do that?

**Comment by bmesnet** [comment]
@boekholt. Could this be done when setting/exporting the SNAP_ROOT variable ?

**Comment by boekholt** [comment]
@bmesnet Pull request #505 is completed. Please close this issue if the change meets your requirements.
Thanks
Sven

**Comment by bmesnet** [comment]
This is more than perfect and will help a lot the user. Thanks a lot @boekholt . Quick and efficient as usual. Thx. Closing the issue
