### ISSUE TITLE
Missing Action Test cases

### ISSUE THREAD

**Issue by ibm-genwqe** [open-power/snap#511]
This issue is to track the missing test files for:

1.) ./actions/hls_sponge/tests/test_0x10141001.sh
2.) ./actions/hls_search/tests/test_0x10141003.sh
3.) ./actions/hls_helloworld/tests/test_0x10141008.sh
4.) ./actions/hdl_nvme_example/tests/test_0x10140001.sh

All Script files are called from "./actions/script/snap_jenkins.sh with "-C 0/1/2/3 and -d NORMAL"
parameters. Please push you code updates into "RC_fix_jenkins" Branch.

**Comment by acastellane** [comment]
Hallo,
in master, valid tests are now existing for hls_helloworld and hls_sponge.
Concerning hls_search, we need to refresh the example, so the test is a dummy one.
Regards.
