### ISSUE TITLE
Add the name of the action in the bitstream file name

### ISSUE THREAD

**Issue by bmesnet** [open-power/snap#545]
Is it possible to have the name of the action in  the bitstream name? This is simpler for a user to find in a glance what the bitstream file is related to (even if we can copy to the P8 server, then download it into the FPGA and then get the information with the snap_maint).

**Comment by ThomasFuchs** [comment]
I Bruno,  I have implement and merged this new feature into master. Please see also #791

**Comment by bmesnet** [comment]
Great improvement. Thanks. It works perfectly
