### ISSUE TITLE
PSL P9 with S121B: snap_example timeout

### ISSUE THREAD

**Issue by joergkayser** [open-power/snap#548]
PSLSE=capi2 cc2d565 2017-12-13, SNAP=master ac0adf8 2017-12-12, 
card=S121B (incl BRAM), action= hdl_example
snap_example -a2 -S1 -B0 -A4096 -t260 fails with timeout, 
the output buffer shows '00 00' after address 0xc80.
AET is available under /afs/bb/proj/fpga/framework/jkayser/snap_master/hardware/sim/ies/20171214_151607

**Comment by ThomasFuchs** [comment]
This is was a problem in the new DMA logic for P9P.

**Comment by joergkayser** [comment]
solved and merged into master
