### ISSUE TITLE
make model fails if outdated PSL_DCP (for N250S)

### ISSUE THREAD

**Issue by bmesnet** [open-power/snap#565]
On SuperVessel, with PSLSE tag v3.1 + latest SNAP ( e0301af), when selecting the N250S which has an old PSL_DCP, the **make model** fails
make[4] :  *** check_snap_settings Error 1
...
Problem doesn't appears with KU3 which has a correct PSL_DCP

**Comment by boekholt** [comment]
Thomas is currently changing the way of how we are handling the PSL DCP in the creation of XILINX project during the build process.
That will solve this issue.

**Comment by bmesnet** [comment]
Corrected and tested ok. Thanks
