### ISSUE TITLE
XSim elaboration fails with on-card DRAM [Vivado dependency]

### ISSUE THREAD

**Issue by jsvogt** [open-power/snap#70]
Xilinx XSIM modelbuild still fails on models with DDR3 RAM and gates the merge into the master branch. Vivado 2015.4 failed with VRFC 10-327 array size is larger than 2**31
Vivado 2016.3 fails with a memory leak described in SR10375645 and SR10377642.

**Comment by jsvogt** [comment]
Re-test with Vivado 2017.1 needed, or close due to change to Xilinx MIG memory model?

**Comment by joergkayser** [comment]
xsim on DDR3 works, since we switched to the Xilinx/Micron memory model
