### ISSUE TITLE
Simulation with XSIM and a coredump in the end

### ISSUE THREAD

**Issue by luyong6** [open-power/snap#720]
When using **XSIM**,
There is a coredump after the simulation is done,  shown as following in the screencopy. 
I tested both hls_helloworld and hls_bfs, they both have the same problem. 
It may not harm but still annoying.  
![default](https://user-images.githubusercontent.com/23333783/38544908-56946c92-3cdb-11e8-8c66-c31af7f4eb77.png)
![default](https://user-images.githubusercontent.com/23333783/38544916-5ba5ac00-3cdb-11e8-95e6-a8e65f644cd3.png)

**Comment by joergkayser** [comment]
@luyong6 we dont see any core dump with Vivado 2018.1 anymore.
All dumps were seen with 2017.4, so if you see your dump in 2018, then please reopen
