### ISSUE TITLE
cloud doesnt open GUI with 'make snap_config'

### ISSUE THREAD

**Issue by joergkayser** [open-power/snap#726]
When following the README guidelines in "SNAP-DESKTOP V0.1.1", the step 'make snap_config' fails to open the GUI, when $SIMULATOR is not defined. We missed this bug in regression, as we always define $SIMULATOR.
The bug can be fixed by changing snap_env line 151 from $SIMULATOR to "$SIMULATOR" to prevent having a unary operator.

**Comment by boekholt** [comment]
Fix is in pull request #727

**Comment by joergkayser** [comment]
This works in our 'cloud regression'. @kenhill  Will you pick this as well ?

**Comment by joergkayser** [comment]
waiting for the next $CLOUD_BRANCH, this is still 1.4.1 and does not contain a fix yet

**Comment by joergkayser** [comment]
The SNAP_DESKTOP v0.1.1 still uses $CLOUD_BRANCH=1.4.1, and snap_env line 151 fails and the GUI cannot be opened, see above description.
Please fix as described above. Thanks

**Comment by kenhill** [comment]
@joergkayser, sorry for the delay. SNAP_DESKTOP v1.0.2 uses SNAP v1.4.2.

Is this still a problem?

**Comment by joergkayser** [comment]
@kenhill SNAP v1.4.2 incorporates the fix #727 from @boekholt. When I call https://platform.jarvice.com, then I see SNAP_DESKTOP v0.1.1(408985), which sets the environment variable SNAP_DEV_RELEASE=V0.1.1
How can I upgrade SNAP_DESKTOP from v0.1.1 to v1.0.2 ?

**Comment by kenhill** [comment]
@joergkayser not sure why see the older version. Can you try the new portal: https://mc.jarvice.com

The apps should be public under the `Compute` tab.

**Comment by joergkayser** [comment]
The todays Login finally shows SNAP_DESKTOP v1.0.2 and uses CLOUD_BRANCH v1.4.2, which solves this problem. Thanks
