### ISSUE TITLE
10140000_kill_test.sh timeout + unable to attach action

### ISSUE THREAD

**Issue by bmesnet** [open-power/snap#785]
10140000_kill_test.sh timeout on P8+8K5 and P9+RCXVUP and P9+NSA241 (Lu Yong's test)
```
[main] Exit rc:0
(1) Check if card is replying to a single memcopy request (1)..
action_wait_idle Timeout Error
err: Single snap_example took to long, please review results!
```

extending timeout with -t5 option get rids of timeout, but get to next error:
```
(4) Check if card is replying to a single memcopy request...
Error: Can not attach Action; 10140000
```

**Comment by boekholt** [comment]
@bmesnet That is very difficult to understand (for me).
What is the exact sequence of commands you are executing?
Could you please paste the output of
```
software/tools/snap_maint -vvv
```

**Comment by bmesnet** [comment]
I don't have the ability to do a screenshot on a P9 but here is the one I have on Marrennes (P8) with an ADK5). I don't have the timeout issue on this one. Could it be different on P9 due to the IRQ?
Did I missed a setting ? Thanks for taking care of that
 ![screenshot on p8_adk5](https://user-images.githubusercontent.com/22619089/43050994-34b49858-8e12-11e8-95c3-58c956c2343a.jpg)

**Comment by bmesnet** [comment]
Closing this issue since never reproduced again
