### ISSUE TITLE
CAPI2.0 SNAP actions hang on certain linux kernels

### ISSUE THREAD

**Issue by luyong6** [open-power/snap#792]
I created several SNAP actions like hls_helloworld, hls_memcopy, hls_mm_test on FX609 (and Semptian card), and I found on following Ubuntu kernel: 
* 4.14.49
* 4.18.0
After running 3-5 times successfully, the application will "hang". No response. 

* 4.15.0 and 4.17.0 don't have the phenomenon. 

Some hints: 
1. Vaibhav has build the cxl module from 4.15.0 into 4.18.0, but the "hang" still happen. 
2. I built afp2 for FX609 and run on 4.18.0, there is no "hang". 
3. "hang" happens at the last MMIO polling.

**Comment by jsvogt** [comment]
Is this still occurring?

**Comment by bmesnet** [comment]
No description + this wasn't faced since a while
