### ISSUE TITLE
Action software.mk clean modification

### ISSUE THREAD

**Issue by shhssdm** [open-power/snap#893]
Hi CAPI-SNAP developers,

Would it be possible to modify the software.mk clean?

Currently, clean is only removing object files in the same directory because of *.o argument.

However, my sw directory has several sub-directories inside and I'd like all object files inside them to be removed as well.

It would be nice if some statements in software.mk can be modified like *.o -> $($(projs)_objs).

Thanks in advance.

**Comment by bmesnet** [comment]
Sure. Please propose some code doing a pull request and we will integrate it after regression tests. This is a community work and we are happy to get all contributions. 
Thanks for improving the code.

**Comment by bmesnet** [comment]
Code is in pull request #894

**Comment by bmesnet** [comment]
Code merged. Can we close this issue?
Thanks for improving the code

**Comment by shhssdm** [comment]
Yes indeed. Thank you also.
