### ISSUE TITLE
jenkins: Automatically test bitstream on real hardware

### ISSUE THREAD

**Issue by fhaverkamp** [open-power/snap#95]
We need a box and we might start without flashing the card. Just taking what is there and running a few tests on the available card.

**Comment by ibm-genwqe** [comment]
I added a file in "software/scripts/snap_jenkins.sh" which gets triggered after a good image build.
The script flashes the cards and runs all test's.
HLS testing is not fully implemented but can be added. The script works on KU3 and FGT card.

**Comment by jsvogt** [comment]
Done, closing
