### ISSUE TITLE
NVMe: ncsim reports TRZGCOC: Possible zero-delay gate oscillation detected

### ISSUE THREAD

**Issue by joergkayser** [open-power/snap#96]
usual debug procedure 'drivers -active' doesn't work and just reports: [Protected]
Cadence tickets filed: 46066272 (Ishan) and 46068020 (Joerg)

**Comment by jsvogt** [comment]
Please recreate with latest Xilinx tools. Address to Xilinx if the problem persists

**Comment by jsvogt** [comment]
Can't recreate any more. Will not fix. Re-open if this problem hits again.
