### ISSUE TITLE
FGT: System reports no CAPI card after Flash update

### ISSUE THREAD

**Issue by ibm-genwqe** [open-power/snap#99]
I loaded "fw_master_noDDR3_0110_049_fgt.bit" into Flash GT card over JTAG Debugger after Power on (VIVADO 16.04 LAB). The FGT Card appears as a CAPI card as expected after Linux gets loaded.
Running "stage2 -a2" to test Host -> Host DMA was successful.
Next step was to flash the bin file. "sudo ./flash_FGT fw_master_noDDR3_0110_049_fgt.bin 0" 
This was also ok.
Than i reset the card "echo 1 > /sys/class/cxl/card0/reset"
The CAPI Card disappeared. I assume that either my image is wrong, or flashing did not work or
the Factory default side was started.

**Comment by jsvogt** [comment]
This was a bug of the PSL for the FGT card. It is fixed now
